#!/bin/bash
### Calculator for both integer and floating point numbers, 
### Arguments: 1st operand , operation, 2nd operation
### Output: Scripts returns result based on operation specified by the operation argument 
### Exit Codes:
#       0: Normal termination
#       1: Insufficient parameters
#       2: 1st operand is not a number
#       3: 2nd operand is nor a number
#       4: Invalid operation
#       5: 2nd operand is Zero (in case of division only)

if [ ${#} -ne 3 ]
then
        echo "Insufficient paramters"
        exit 1
fi
OP1=${1}
OP2=${3}
OP=${2}

### Check if first operand is a number or not 
CHK=$(echo "${OP1}" | grep -c "[^0.0-9.9]")
if [ ${CHK} -eq 1 ]
then
        echo "First operand is not a number"
        exit 2
fi
### Check if second operand is a number or not
CHK=$(echo "${OP2}" | grep -c "[^0.0-9.9]")
if [ ${CHK} -eq 1 ]
then
        echo "Second operand is not a number"
        exit 2
fi

case "${OP}" in
        "add")
                RES=$[OP1+OP2]
                ;;
        "sub")
                RES=$[OP1-OP2]
                ;;
        "mul")
                RES=$[OP1*OP2]
                ;;
        "div")
                if [ ${OP2} -eq 0 ]
                then
                        echo "Math Error: Division By Zero"
                        exit 5
                fi
                RES=$(printf %.4f\\n "$((1000 * ${OP1}/${OP2}  ))e-3")
                ;;
        *)
                echo "Invalid operation"
                exit 4
                ;;
esac
echo "Result = ${RES}"
exit 0

